package common;

public enum RequestType {
    ADD_GAME,
    REMOVE_GAME,
    UPDATE_GAME_RISK,
    UPDATE_GAME_BET_LIMITS,
    GET_PROVIDER_STATS,
    GET_PLAYER_STATS,
    INIT_PROVIDER_REDUCE_JOB,
    INIT_PLAYER_REDUCE_JOB,
    MAP_PROVIDER_STATS,
    MAP_PLAYER_STATS,
    SUBMIT_PROVIDER_MAP_RESULT,
    SUBMIT_PLAYER_MAP_RESULT,
    GET_ALL_GAMES,
    SEARCH_GAMES,
    PLACE_BET,
    ADD_BALANCE,
    HEALTH_CHECK
}
